-- Run this in Supabase SQL editor.
-- 1) Profile table: stores public game identity (username) bound to auth.users
create table if not exists public.arcade_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint arcade_profiles_username_format check (username ~ '^[a-z0-9_.-]{3,24}$')
);

alter table public.arcade_profiles enable row level security;

create policy "profiles are publicly readable"
on public.arcade_profiles
for select
using (true);

create policy "user can insert own profile"
on public.arcade_profiles
for insert
with check (auth.uid() = id);

create policy "user can update own profile"
on public.arcade_profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- Keep updated_at fresh.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists arcade_profiles_set_updated_at on public.arcade_profiles;
create trigger arcade_profiles_set_updated_at
before update on public.arcade_profiles
for each row execute function public.set_updated_at();

-- 2) Leaderboard table update to persist user_id + username snapshot.
create table if not exists public.turborace_leaderboard (
  id bigint generated by default as identity primary key,
  track_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  username text not null,
  time_ms integer not null check (time_ms >= 0),
  created_at timestamptz not null default now()
);

alter table public.turborace_leaderboard
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists username text,
  add column if not exists time_ms integer,
  add column if not exists created_at timestamptz default now();

update public.turborace_leaderboard
set username = coalesce(nullif(trim(username), ''), 'Anonymous')
where username is null or trim(username) = '';

alter table public.turborace_leaderboard
  alter column username set not null,
  alter column time_ms set not null,
  alter column created_at set not null;

alter table public.turborace_leaderboard enable row level security;

create policy "leaderboard is readable"
on public.turborace_leaderboard
for select
using (true);

create policy "authenticated users can submit times"
on public.turborace_leaderboard
for insert
to authenticated
with check (
  user_id is null or auth.uid() = user_id
);

create index if not exists turborace_leaderboard_track_time_idx
on public.turborace_leaderboard (track_id, time_ms asc, created_at asc);
